DROP TABLE IF EXISTS messages;

CREATE TABLE messages
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id TEXT NOT NULL,
    author_name TEXT NOT NULL,
    message_text TEXT NOT NULL,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_messages_room_created_at
    ON messages (room_id, created_at_utc DESC, id DESC);
